version: '3'

services:
  database:
        image: mysql:latest
        container_name: 'database'
        ports:
          - "3306:3306"
        volumes:
          - /mysql_data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: cloud
        restart: on-failure

  frontend:
    build: 'frontend/'
    image: 'frontend:1.0'
    ports:
      - '8080:8080'

  backend:
    build: ./
    image: 'backend:1.0'
    ports:
      - '8090:8090'
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/cloud